### ISSUE TITLE
Update missing icons

### ISSUE THREAD

**Issue by RoyvanEmpel** [tsutoringo/vue-material-symbols#2]
Hi,

Soms of the new icons like "splitscreen_vertical_add" are unavailable in this package.

Would you be able to update the NPM with the newer icons?

Thank you.

**Comment by tsutoringo** [comment]
v1.0.1 published with many icons!
https://github.com/tsutoringo/vue-material-symbols/commit/fa41c0e952aaa1df0c11c478930707f901c8d503
https://www.npmjs.com/package/vue-material-symbols/v/1.0.1
